# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_logistic_regression_classifier_model
display_name: Train a Logistic Regression Classifier Model
version: 1
type: command
inputs:
  training_data: 
    type: uri_folder
  regularization_rate: 
    type: number
    default: 0.01
outputs:
  model_output_logistic_reg:
    type: uri_folder
code: ../src
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python train-logistic-regression.py 
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.regularization_rate}}
  --model_output_logistic_reg ${{outputs.model_output_logistic_reg}}
# </component>
